spring.application.name=demo

# Connexion à ta nouvelle base dédiée
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/webmap
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ON SUPPRIME LA LIGNE DU DIALECTE (La cause du crash)

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update